"""
Django settings for sito_ranieri project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_1g(#s7j2+x@u$87m*xyn1++xqf1z8b79s)^c!@7kc9tzsh6i8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*', '192.168.0.101']
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tributo',
    'qr_code', 
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sito_ranieri.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media', #aggiunta per provare sfondo immagine 8/6/2026
            ],
        },
    },
]

WSGI_APPLICATION = 'sito_ranieri.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

import os

# URL per accedere ai file tramite browser
MEDIA_URL = '/media/'

# Percorso fisico sul tuo Debian della cartella dei file caricati
MEDIA_ROOT = os.path.join(BASE_DIR, 'media-serve')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os

# Configurazione base comune
EMAIL_HOST = 'smtp.gmail.com'  # CORRETTO: Rimosso '://' e inserito il server SMTP di Google
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'cimmino.angel@gmail.com'

# CORRETTO: Assegnata direttamente la password delle app senza il cancelletto del commento
EMAIL_HOST_PASSWORD = 'tomwftyemcsacrra' 

DEFAULT_FROM_EMAIL = f'Sito Ranieri <{EMAIL_HOST_USER}>'

# SE SEI SU PYTHONANYWHERE: Usa Gmail reale (il controllo sulla cartella HOME funziona)
if 'pythonanywhere' in os.environ.get('HOME', ''):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    # SE SEI IN LOCALE (Debian): Salva i file nella cartella di test
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'email-inviate')





STRIPE_PUBLIC_KEY = "pk_test_51TY5oDI0KegpLuHlh4Zvmy9y6CtBhYYHLyHXV7vTK9ggseu1Q477QGQF6MyXWbsN9BB62PmDOqlS4AFE0WV60DAo00pV33GrdS"
STRIPE_SECRET_KEY = "sk_test_51TY5oDI0KegpLuHl79ULm8jcM7j3mVGyrblePEuV9ZiFeEtNoU3LW7L14pydgT3mdaeykcBRsUYv1eDviB1lCyVA00mqExHpUX"
