# Generated by Django 5.2.14 on 2026-06-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('anno_uscita', models.IntegerField()),
                ('testo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luogo', models.CharField(max_length=200)),
                ('citta', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
