# Generated by Django 5.2.14 on 2026-06-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_sezione', models.CharField(default='La Storia', max_length=200)),
                ('testo_completo', models.TextField()),
                ('anno_inizio_carriera', models.IntegerField(default=1964)),
            ],
        ),
    ]
