# Generated by Django 5.2.14 on 2026-06-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0002_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='biografia',
            name='foto_artista',
            field=models.ImageField(blank=True, null=True, upload_to='biografia/'),
        ),
        migrations.AddField(
            model_name='canzone',
            name='copertina',
            field=models.ImageField(blank=True, null=True, upload_to='copertine/'),
        ),
        migrations.AddField(
            model_name='concerto',
            name='locandina',
            field=models.ImageField(blank=True, null=True, upload_to='locandine/'),
        ),
    ]
