# Generated by Django 5.2.14 on 2026-06-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0003_biografia_foto_artista_canzone_copertina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canzone',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
