# Generated by Django 5.2.14 on 2026-06-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0004_canzone_prezzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='concerto',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=6),
        ),
    ]
