# Generated by Django 5.2.14 on 2026-06-02 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0005_concerto_prezzo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partecipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('codice_biglietto', models.CharField(max_length=100, unique=True)),
                ('data_acquisto', models.DateTimeField(auto_now_add=True)),
                ('concerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipanti', to='tributo.concerto')),
            ],
        ),
    ]
