# Generated by Django 5.2.14 on 2026-06-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0006_partecipante'),
    ]

    operations = [
        migrations.AddField(
            model_name='partecipante',
            name='utilizzato',
            field=models.BooleanField(default=False),
        ),
    ]
