# Generated by Django 5.2.14 on 2026-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0007_partecipante_utilizzato'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSpettacolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('url_embed', models.URLField(help_text="Inserisci il link 'embed' di YouTube (es: https://youtube.comcodice)")),
                ('data_aggiunta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Video Spettacoli',
            },
        ),
    ]
