# Generated by Django 5.2.14 on 2026-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0008_videospettacolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videospettacolo',
            name='titolo',
            field=models.CharField(max_length=300),
        ),
    ]
