# Generated by Django 5.2.14 on 2026-06-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0009_alter_videospettacolo_titolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videospettacolo',
            name='url_embed',
            field=models.URLField(help_text="Inserisci il link 'embed' di YouTube (es: https://youtube.com)", max_length=500),
        ),
    ]
