# Generated by Django 5.2.14 on 2026-06-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0010_alter_videospettacolo_url_embed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videospettacolo',
            name='url_embed',
        ),
        migrations.AddField(
            model_name='videospettacolo',
            name='file_video',
            field=models.FileField(blank=True, help_text='Carica un file video (es. formato .mp4)', null=True, upload_to='video/'),
        ),
        migrations.AlterField(
            model_name='videospettacolo',
            name='titolo',
            field=models.CharField(max_length=200),
        ),
    ]
