# Generated by Django 5.2.15 on 2026-06-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0011_remove_videospettacolo_url_embed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concerto',
            name='data',
            field=models.DateField(),
        ),
    ]
