# Generated by Django 5.2.15 on 2026-06-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0012_alter_concerto_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_foto', models.CharField(blank=True, max_length=200, verbose_name='Didascalia Foto')),
                ('immagine', models.ImageField(max_length=255, upload_to='gallery/', verbose_name='File Immagine')),
            ],
            options={
                'verbose_name_plural': 'Foto Gallery',
            },
        ),
        migrations.CreateModel(
            name='Video_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_video', models.CharField(max_length=200, verbose_name='Titolo del Video')),
                ('url_video', models.URLField(verbose_name='Link YouTube/Vimeo')),
            ],
            options={
                'verbose_name_plural': 'Video Gallery',
            },
        ),
        migrations.DeleteModel(
            name='VideoSpettacolo',
        ),
        migrations.AlterModelOptions(
            name='biografia',
            options={'verbose_name_plural': 'Biografie'},
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='anno_inizio_carriera',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='foto_artista',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='testo_completo',
        ),
        migrations.RemoveField(
            model_name='biografia',
            name='titolo_sezione',
        ),
        migrations.AddField(
            model_name='biografia',
            name='data_evento',
            field=models.DateField(default='2026-06-16', verbose_name="Data dell'Evento"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biografia',
            name='descrizione',
            field=models.TextField(default='Descrizione provvisoria', verbose_name='Descrizione dettagliata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biografia',
            name='luogo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Luogo'),
        ),
        migrations.AddField(
            model_name='biografia',
            name='titolo_evento',
            field=models.CharField(default='Titolo evento provvisorio', max_length=200, verbose_name='Titolo Evento/Concerto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foto_gallery',
            name='biografia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='tributo.biografia', verbose_name="Collegato all'evento"),
        ),
        migrations.AddField(
            model_name='video_gallery',
            name='biografia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tributo.biografia', verbose_name="Collegato all'evento"),
        ),
    ]
