# Generated by Django 5.2.15 on 2026-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0013_foto_gallery_video_gallery_delete_videospettacolo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video_gallery',
            name='url_video',
        ),
        migrations.AddField(
            model_name='video_gallery',
            name='file_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos/', verbose_name='File Video (Formato MP4 consigliato)'),
        ),
    ]
