# Generated by Django 5.2.15 on 2026-06-16 13:31

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributo', '0014_remove_video_gallery_url_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuoModello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenuto')),
            ],
        ),
    ]
